// !Signup
export const signup = async (req, res) => {
  try {
  } catch (error) {
    res.status(401).json({ success: false, message: error.message });
  }
};
// !Login
export const login = async (req, res) => {
  try {
  } catch (error) {
    res.status(401).json({ success: false, message: error.message });
  }
};// !Logout
export const logout = async (req, res) => {
  try {
  } catch (error) {
    res.status(401).json({ success: false, message: error.message });
  }
};

